# Generated by Django 5.1.7 on 2025-03-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
