# Generated by Django 5.1.7 on 2025-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customgroup_is_active_alter_customgroup_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
