# Generated by Django 5.1.7 on 2025-03-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customgroup_updated_at_customuser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
    ]
