# Generated by Django 5.1.7 on 2025-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customgroup_updated_by_customuser_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
