# Generated by Django 5.1.7 on 2025-03-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customgroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='removed by', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated by+', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='removed by', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated by+', to='users.customuser'),
        ),
    ]
