# Generated by Django 5.1.7 on 2025-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSessionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('session_key', models.CharField(max_length=40)),
            ],
        ),
    ]
