# Generated by Django 5.1.7 on 2025-04-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_emailsessionmap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSessionMap',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
