# Generated by Django 5.1.7 on 2025-04-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_loyaltypoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoyaltyPoint',
        ),
    ]
