# Generated by Django 5.1.7 on 2025-04-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_loyaltypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltypoint',
            name='amount',
        ),
    ]
