# Generated by Django 5.1.7 on 2025-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_loyaltypoint_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField()),
            ],
        ),
    ]
