# Generated by Django 5.1.7 on 2025-04-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_loyaltypointlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypointlimit',
            name='total_choice',
            field=models.CharField(choices=[('SUBTOTAL', 'subtoal'), ('TOTAL', 'total')], default='subtoal', max_length=10),
        ),
    ]
