# Generated by Django 5.1.7 on 2025-04-10 06:07

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_loyaltypointlimit_total_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltypoint',
            name='expiry',
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='expires_at',
            field=models.DateTimeField(default=users.models.get_expiry),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 10, 6, 7, 31, 14372, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
