# Generated by Django 5.1.7 on 2025-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_loyaltypoint_expiry_loyaltypoint_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
