# Generated by Django 5.1.7 on 2025-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_loyaltypoint_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
