# Generated by Django 5.1.7 on 2025-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_loyaltypoint_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
