# Generated by Django 5.1.7 on 2025-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_loyaltypoint_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypoint',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loyaltypointlimit',
            name='total_choice',
            field=models.CharField(choices=[('SUBTOTAL', 'Subtoal'), ('TOTAL', 'Total')], default='Subtoal', max_length=10),
        ),
    ]
