# Generated by Django 5.1.7 on 2025-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_loyaltypoint_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('is_open', models.BooleanField()),
            ],
        ),
    ]
