# Generated by Django 5.1.7 on 2025-04-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_storetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreTime',
        ),
    ]
