# Generated by Django 5.1.7 on 2025-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_storestatus_remove_storetime_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestatus',
            name='update_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
