# Generated by Django 5.1.7 on 2025-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_storestatus_update_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStatusLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.CharField(max_length=100)),
                ('log_status_code', models.IntegerField()),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
