# Generated by Django 5.1.7 on 2025-04-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_storestatuslogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storestatuslogs',
            old_name='log_status_code',
            new_name='respose_status_code',
        ),
    ]
