# Generated by Django 5.1.7 on 2025-04-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_log_status_code_storestatuslogs_respose_status_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storestatuslogs',
            old_name='respose_status_code',
            new_name='response_status_code',
        ),
    ]
