# Generated by Django 5.1.7 on 2025-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_rename_respose_status_code_storestatuslogs_response_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestatuslogs',
            name='response_status_code',
            field=models.CharField(max_length=10),
        ),
    ]
