# Generated by Django 5.1.7 on 2025-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_storestatuslogs_response_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetime',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storetime',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
