# Generated by Django 5.1.7 on 2025-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dilivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
