# Generated by Django 5.1.7 on 2025-03-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_order_subtotal_alter_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dilivery_charge',
            new_name='delivery_charge',
        ),
    ]
