# Generated by Django 5.1.7 on 2025-04-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_paid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
            ],
        ),
    ]
