# Generated by Django 5.1.7 on 2025-04-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_webpushtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebPushToken',
        ),
    ]
