# Generated by Django 5.1.7 on 2025-04-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_delete_webpushtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='reference_id',
        ),
    ]
