# Generated by Django 5.1.7 on 2025-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_transaction_id_payment_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
