# Generated by Django 5.1.7 on 2025-04-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_payment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
    ]
