# Generated by Django 5.1.7 on 2025-04-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDIND', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('READY', 'Ready'), ('CANCEL', 'Cancel')], default='PENDIND', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery'), ('DINE_IN', 'Dine_in')], default='PICKUP', max_length=20, null=True),
        ),
    ]
