# Generated by Django 5.1.7 on 2025-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_order_status_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='open_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='open_time',
            field=models.TimeField(null=True),
        ),
    ]
