# Generated by Django 5.1.7 on 2025-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_category_close_time_category_open_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base64_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
