# Generated by Django 5.1.7 on 2025-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_base64_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='squence_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
