# Generated by Django 5.1.7 on 2025-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_category_squence_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('squence_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
