# Generated by Django 5.1.7 on 2025-04-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_squence_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
