# Generated by Django 5.1.7 on 2025-04-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_delete_subcategory_category_subcategory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='squence_number',
            new_name='sequence_number',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='subcategory_squence_number',
            new_name='subcategory_sequence_number',
        ),
    ]
