# Generated by Django 5.1.7 on 2025-04-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_squence_number_category_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
