# Generated by Django 5.1.7 on 2025-04-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_category_close_time_alter_category_open_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'sequence_number')},
        ),
    ]
