# Generated by Django 5.1.7 on 2025-04-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_category_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
