# Generated by Django 5.1.7 on 2025-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_category_deleted_at_category_deleted_by_and_more'),
        ('users', '0041_alter_storetime_close_time_alter_storetime_open_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_name_sequence_number',
        ),
        migrations.AlterField(
            model_name='category',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'sequence_number'), name='unique_name_sequence_number'),
        ),
    ]
